Rack app
Svawek/rack_app pull request #1
Opened 2019-06-23 20:09 UTC by Svawek

2019-06-24 05:53 UTC, BubuntuClu requested changes

2019-06-24 05:53 UTC, BubuntuClu commented on app.rb
> +class App
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса. Поэтому задача этого класса принять параметры и предоставить некоторое API, например:
```
fmt = TimeFormatter.new(params['format'])
fmt.call
fmt.success?
fmt.result
```

2019-06-24 05:54 UTC, BubuntuClu commented on middleware/view_time.rb
> +  AVAILABLE_QUERIES = %w(year month day hour minute second)
это может быть хэшем, где ключ это слово, а значение структура подходящая для `strftime` : `%H`, `%M`, `%Y` и тд

2019-06-26 05:18 UTC, BubuntuClu requested changes

2019-06-26 05:18 UTC, BubuntuClu commented on app.rb
> +    @extra_queries = @queries - AVAILABLE_QUERIES
это тоже хорошо бы сделать в классе TimeFormatter. в нем можно сделать вспомогательный метод `valid?/success?` для определения нет ли в нем ненужных форматов

2019-06-26 05:18 UTC, BubuntuClu commented on app.rb
> +    { 'Content-Type' => 'text/plain' }
Заголовки по умолчанию стоит вынести в константу.

2019-06-26 05:18 UTC, BubuntuClu commented on app.rb
> +  AVAILABLE_QUERIES = %w(year month day hour minute second)
этот класс не должен знать ни о каких разрешенных переменных, это проверяет TimeFormatter

2019-06-26 05:18 UTC, BubuntuClu commented on app.rb
> +    if @answer_status == 200
тут скорее нужно сделать обратную логику, не от статуса определять стоит ли формат вызывать, а на оборот на основе вызова формата, определять какой статус получается

2019-06-26 20:28 UTC, BubuntuClu commented on time_formatter.rb
> +    [ "#{@time.join("-")}\n" ]
это тоже небольшая зависимость от реализации твоего класса app. просто строку должно возвращать. если ты куда-то вынесешь этот класс и будешь там использовать, то обернутось в массив ничем не обусловлена

2019-06-26 23:00 UTC, psylone requested changes

2019-06-26 23:00 UTC, psylone commented on app.rb
> +      fmt = TimeFormatter.new(env["QUERY_STRING"])
Проще использовать `Rack::Request#params`.

2019-06-26 23:00 UTC, psylone commented on time_formatter.rb
> +    @queries = queries.delete_prefix("format=").split("%2C")
По факту, это строка запроса, то есть `query` (в единственном числе).

2019-06-26 23:00 UTC, psylone commented on time_formatter.rb
> +      @time << time_now.strftime(AVAILABLE_TIME_FORMATTE[query])
Проще сначала сджоинить по `-`, а потом один раз вызвать `strftime`.

2019-06-26 23:00 UTC, psylone commented on app.rb
> +    [@status, HEADERS, body(env)]
`@status` вычислится в `nil`.

2019-06-26 23:00 UTC, psylone commented on app.rb
> +    if check_request_method?(env["REQUEST_METHOD"]) & check_request_path?(env["REQUEST_PATH"])
Вот это вот всё на самом деле больше относится к `call`, чем к `body`.

2019-06-26 23:00 UTC, psylone commented on app.rb
> +    if check_request_method?(env["REQUEST_METHOD"]) & check_request_path?(env["REQUEST_PATH"])
Также мы здесь конкретно проверяем path, связанный с `/time`, поэтому лучше так метод и назвать `check_time_request`.

2019-06-26 23:00 UTC, psylone commented on app.rb
> +    if check_request_method?(env["REQUEST_METHOD"]) & check_request_path?(env["REQUEST_PATH"])
`check_request_path?` читается как _проверить путь запроса?_, хотя метод выполняет несколько иную обязанность.

2019-06-26 23:00 UTC, psylone commented on app.rb
> +    [@status, HEADERS, body(env)]
Здесь не помешает сделать такую структуру метода:

```ruby
def call(env)
  case path
  when '/time'
    time_response
  else
    not_found_response
  end
end
```

2019-06-28 03:53 UTC, BubuntuClu commented on app.rb
> +    [404, HEADERS, [ "404. No such page!\n" ]]
`response(404, [ "404. No such page!\n" ])`

2019-06-28 08:58 UTC, psylone commented on app.rb
> +    Rack::Response.new(body, status, HEADERS)
Не забывай вызывать метод `finish`: https://www.rubydoc.info/gems/rack/Rack/Response

2019-06-28 09:01 UTC, psylone commented on time_formatter.rb
> +    end
Можно так: `format = @query.map { |q| AVAILABLE_TIME_FORMATTE[q] }`.

2019-06-28 09:15 UTC, psylone approved these changes

2019-06-30 20:10 UTC, merged